{% set name = "xcube-smos" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-smos/archive/v{{ version }}.tar.gz
  sha256: 3f3a42bfb93264ef43ec73dc0fd278180924d7f387b9af9eb1c35bc87eb9b54c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    # Requires kerchunk
    - nckcidx = xcube_smos.nckcindex.cli:cli

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - click
    - fsspec
    - h5netcdf
    - h5py
    - importlib_resources
    - numpy
    - numba
    - pandas
    - xarray
    - xcube
    # Optional
    - kerchunk

test:
  imports:
    - xcube_smos
    - xcube_smos.store

about:
  home: https://github.com/dcs4cop/xcube-smos
  summary: 'xcube data store for ESA EE SMOS Level-2 multi-level datasets'
  description: |
    xcube-smos is a data store plug-in for xcube, providing experimental
    support for ESA EE SMOS Level-2 data.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - forman
    - pont-us
    - ruchimotwaniBC
    - TejasMorbagal
    - thomasstorm
    - TonioF
