{% set name = "xcube-smos" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-smos/archive/v{{ version }}.tar.gz
  sha256: 1cef96683d4a52155ebb7b711f343e81add72b60d1746696d8a5afc95744fd1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    # Requires kerchunk
    - nckcidx = xcube_smos.nckcindex.cli:cli

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - click
    - fsspec
    - h5netcdf
    - h5py
    - importlib_resources
    - numpy
    - numba
    - pandas
    - requests
    - xarray
    - xcube >=1.2

test:
  imports:
    - xcube_smos
    - xcube_smos.store

about:
  home: https://github.com/dcs4cop/xcube-smos
  summary: xcube data store for ESA EE SMOS Level-2 data
  description: |
    xcube-smos is a data store plug-in for xcube, providing experimental
    support for ESA EE SMOS Level-2 data.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - forman
    - pont-us
    - ruchimotwaniBC
    - TejasMorbagal
    - thomasstorm
    - TonioF
