{% set name = "xcube-smos" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-smos/archive/v{{ version }}.tar.gz
  sha256: 442187e9ee508f9780283f23d0fff0327688af91eab3f82cd3db6b4df9c14915

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - nckcidx = xcube_smos.nckcindex.cli:cli

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - click
    - boto3
    - h5netcdf >=1.1.0,<1.2
    - h5py >=3.8,<3.9
    - kerchunk >=0.2,<0.3
    - xcube
    
test:
  imports:
    - xcube_smos

about:
  home: https://github.com/dcs4cop/xcube-smos
  summary: 'xcube data store for ESA EE SMOS Level-2 multi-level datasets'
  description: |
    xcube-smos is a data store plug-in for xcube, providing experimental
    support for ESA EE SMOS Level-2 multi-level datasets.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - forman
    - pont-us
    - ruchimotwaniBC
    - TejasMorbagal
    - thomasstorm
    - TonioF
