{% set python_min = "3.10" %}
{% set name = "xcube-smos" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-smos/archive/v{{ version }}.tar.gz
  sha256: 818c9a5a756bee8a113c009c1eb9009bbc421b2016ea426214f69e726b3ade7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    # Requires kerchunk
    - nckcidx = xcube_smos.nckcindex.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - click
    - fsspec
    - h5netcdf
    - h5py
    - importlib_resources
    - numpy
    - numba
    - pandas
    - requests
    - xarray
    - xcube >=1.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - xcube_smos
    - xcube_smos.store

about:
  home: https://github.com/dcs4cop/xcube-smos
  summary: xcube data store for ESA EE SMOS Level-2 data
  description: |
    xcube-smos is a data store plug-in for xcube, providing experimental
    support for ESA EE SMOS Level-2 data.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - forman
    - pont-us
    - ruchimotwaniBC
    - TejasMorbagal
    - thomasstorm
    - TonioF
